### ISSUE TITLE
后端启动报错

### ISSUE THREAD

**Issue by zys0505** [griabcrh/vue-activiti-demo#13]
org.activiti.engine.ActivitiException: Could not update Activiti database schema: unknown version from database: '7.0.0.0'
	at org.activiti.engine.impl.db.DbSqlSession.dbSchemaUpdate(DbSqlSession.java:1044) ~[activiti-engine-5.22.0.jar:5.22.0]
	at org.activiti.engine.impl.db.DbSqlSession.performSchemaOperationsProcessEngineBuild(DbSqlSession.java:1422) ~[activiti-engine-5.22.0.jar:5.22.0]
	at org.activiti.engine.impl.SchemaOperationsProcessEngineBuild.execute(SchemaOperationsProcessEngineBuild.java:27) ~[activiti-engine-5.22.0.jar:5.22.0]
	at org.activiti.engine.impl.interceptor.CommandInvoker.execute(CommandInvoker.java:24) ~[activiti-engine-5.22.0.jar:5.22.0]
	at org.activiti.engine.impl.interceptor.CommandContextInterceptor.execute(CommandContextInterceptor.java:57) ~[activiti-engine-5.22.0.jar:5.22.0]
	at org.activiti.spring.SpringTransactionInterceptor$1.doInTransaction(SpringTransactionInterceptor.java:47) [activiti-spring-5.22.0.jar:5.22.0]

**Comment by griabcrh** [comment]
activiti版本和数据库里引擎版本对不上

**Comment by liang-kan** [comment]
亲，如何解决了
